from typing import Protocol

from app.domain.order import CreateOrder, CustomerDetails, OrderView, WarehouseCandidate
from app.domain.shipping_address import Coordinates


class OrderRepository(Protocol):
    async def create(self, command: CreateOrder, key: str) -> tuple[OrderView, bool]: ...

    async def locate(self, order_id: int, coordinates: Coordinates) -> None: ...

    async def candidates(self, order_id: int) -> list[WarehouseCandidate]: ...

    async def reserve(self, order_id: int, warehouse_id: int) -> bool: ...

    async def ensure_customer(self, order_id: int, customer: CustomerDetails) -> None: ...

    async def cancel(self, order_id: int, reason: str) -> None: ...

    async def pay(self, order_id: int, payment_identifier: str | None) -> None: ...

    async def get(self, order_id: int) -> OrderView: ...

    async def list(self, limit: int, offset: int) -> list[OrderView]: ...
