from typing import Protocol

from app.domain.order import CreateOrder, OrderView, WarehouseCandidate
from app.domain.shipping import Coordinates


class OrderRepository(Protocol):
    async def create(
        self, command: CreateOrder, order_idempotency_key: str, payment_idempotency_key: str
    ) -> tuple[OrderView, bool]: ...

    async def locate(self, order_id: int, coordinates: Coordinates) -> None: ...

    async def candidates(self, order_id: int) -> list[WarehouseCandidate]: ...

    async def record_warehouse_decision(
        self,
        order_id: int,
        coordinates: Coordinates,
        ranked: list[tuple[WarehouseCandidate, float]],
    ) -> None: ...

    async def reserve(self, order_id: int, warehouse_id: int) -> bool: ...

    async def cancel(self, order_id: int, reason: str) -> None: ...

    async def start_payment(self, order_id: int) -> None: ...

    async def pay(self, order_id: int, payment_identifier: str | None) -> None: ...

    async def get(self, order_id: int) -> OrderView: ...

    async def list(self, limit: int, offset: int) -> list[OrderView]: ...
